# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('address_text', models.TextField(help_text=b'Address document for search')),
                ('address_nice', models.TextField(blank=True, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('envelope', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
