# Generated by Django 2.0.4 on 2018-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shack', '0003_add_tsv_update_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_text',
            field=models.TextField(help_text='Address document for search'),
        ),
    ]
