# Generated by Django 2.1.7 on 2019-05-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shack', '0005_address_owner'),
    ]

    operations = [
        migrations.RunSQL('''CREATE OR REPLACE FUNCTION shack_address_search_trigger() RETURNS trigger AS $$
begin
  new.tsv :=
    setweight(to_tsvector(coalesce(new.data->>'road_name','')), 'A') ||
    setweight(to_tsvector(coalesce(new.data->>'locality','')), 'A') ||
    setweight(to_tsvector(coalesce(new.data->>'lot_number','')), 'B') ||
    setweight(to_tsvector(coalesce(new.address_text,'')), 'D');
  return new;
end
$$ LANGUAGE plpgsql;'''),
    ]
