# Generated by Django 3.2.4 on 2021-07-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shack', '0008_auto_20210630_1137'),
    ]

    operations = [
        migrations.RunSQL('''CREATE OR REPLACE FUNCTION shack_address_search_trigger() RETURNS trigger AS $$
begin
  new.tsv :=
    setweight(to_tsvector(coalesce(new.data->>'road_name','')), 'A') ||
    setweight(to_tsvector(coalesce(new.data->>'locality','')), 'A') ||
    setweight(to_tsvector(coalesce(new.data->>'lot_number','')), 'B') ||
    setweight(to_tsvector(coalesce(new.data->>'pin','')), 'B') ||
    setweight(to_tsvector(coalesce(new.data->>'reserve','')), 'B') ||
    setweight(to_tsvector(coalesce(new.address_text,'')), 'D');
  return new;
end
$$ LANGUAGE plpgsql;'''),
    ]
