# Generated by Django 3.2.15 on 2022-10-21 00:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shack', '0009_auto_20210701_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
