apiVersion: batch/v1
kind: CronJob
metadata:
  name: caddy-cronjob-import
spec:
  # AWST: 23:11 on day 11, every third month
  schedule: '11 12 11 */3 *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
            - name: caddy-import
              image: ghcr.io/dbca-wa/caddy
              command: ['python']
              args: ['manage.py', 'harvest_cadastre_wfs']
              envFrom:
                - secretRef:
                    name: caddy-env-prod
              env:
                - name: TZ
                  value: 'Australia/Perth'
              resources:
                requests:
                  memory: '256Mi'
                  cpu: '10m'
                limits:
                  memory: '2Gi'
                  cpu: '1000m'
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - mountPath: /tmp
                  name: tmpfs-ram
          volumes:
            - name: tmpfs-ram
              emptyDir:
                medium: 'Memory'
          restartPolicy: Never
          automountServiceAccountToken: false
          tolerations:
            - key: arch
              operator: Equal
              value: arm64
              effect: NoSchedule
